title: 'LiF: Extended'
description: 'Life is Feudal: Your Own, LiFx, mod framework'
theme: just-the-docs
url: https://lifxmod.com
aux_links:
  Supported by Rampart.Games: https://rampart.games
  YoLauncher: https://yolauncher.app
  GitHub: https://github.com/LiF-x
footer_content: >-
  Copyright &copy; 2020-2022 https://github.com/Mjaed. Distributed by an <a
  href="https://github.com/LiF-x/lifxmod.com/blob/main/LICENSE">GPL 3.0
  license.</a><br />Found a problem? Please submit any problems you find here:
  <a href="https://github.com/LiF-x/lifxmod.com/issues">Issues</a>
last_edit_timestamp: true
last_edit_time_format: '%b %e %Y at %I:%M %p'
callouts:
  important:
    color: blue
    opacity: 0.3